site_name: My Study Guide documentation
# repo_url: https://workflow-nacho.github.io/

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan

nav:
  - Overview: 'index.md'

