site_name: My Study Guide documentation
# repo_url: https://workflow-nacho.github.io/

theme:
  name: material
  font:
    text: Monserrat
  palette:
    primary: teal
    accent: cyan
  logo: assets/images/TxFlow_Geometric_Logo_Icon_White_on_Transparent.png
  favicon: assets/images/favicon.png

nav:
  - Overview: 'index.md'

